export const dataMatches = [
  {
    id: 0,
    user: 4,
    meta: {
      game: 1,
      mode: "Team deathmatch",
      map: 10,
      agent: 12,
      dateTimeStarted: "",
      dateTimeEnded: "4 min. ago",
      duration: "38m 26s",
      averageRank: 4,
      text: "We won big time!",
      media: {
        url: "https://res.cloudinary.com/gloot/video/upload/v1691649715/Stryda/demo/game%20footage/B1654A845109D7761_0_3.final.mp4",
      },
    },
    stats: {
      hasWon: true,
      time: "08:10 PM",
      duration: "24m 12s",
      score: {
        team1: 12,
        team2: 9,
      },
      mainStats: [
        {
          label: "Placement",
          value: "#3",
        },
        {
          label: "K/D/A",
          value: "17/17/10",
        },
        {
          label: "K/D",
          value: "1.00",
        },
        {
          label: "ADR",
          value: "175",
        },
        {
          label: "ACS",
          value: "175",
        },
        {
          label: "HS%",
          value: "15.4%",
        },
        {
          label: "KAST",
          value: "64.0%",
        },
      ],
      leaderboard: {
        team1: [
          {
            id: 0,
            agent: 3,
            nickname: "FriendlyFire",
            tag: "2410",
            rank: 6,
            isPlus: true,
          },
          {
            id: 1,
            agent: 5,
            nickname: "shikari",
            tag: "1901",
            rank: 5,
            isPlus: true,
          },
          {
            id: 2,
            agent: 1,
            nickname: "glenn",
            tag: "2321",
            rank: 3,
            isPlus: false,
          },
          {
            id: 3,
            agent: 6,
            nickname: "sooshy",
            tag: "2321",
            rank: 2,
            isPlus: false,
          },
          {
            id: 4,
            agent: 7,
            nickname: "sabsab",
            tag: "2321",
            rank: 1,
            isPlus: false,
          },
        ],
        team2: [
          {
            id: 0,
            agent: 2,
            nickname: "quickyKiller",
            tag: "2413",
            rank: 7,
            isPlus: true,
          },
          {
            id: 1,
            agent: 5,
            nickname: "InifintyWar",
            tag: "1197",
            rank: 5,
            isPlus: true,
          },
          {
            id: 2,
            agent: 9,
            nickname: "glenn",
            tag: "2321",
            rank: 3,
            isPlus: false,
          },
          {
            id: 3,
            agent: 10,
            nickname: "sooshy",
            tag: "2321",
            rank: 2,
            isPlus: false,
          },
          {
            id: 4,
            agent: 11,
            nickname: "sabsab",
            tag: "2321",
            rank: 1,
            isPlus: false,
          },
        ],
      },
    },
    achievements: [
      {
        text: "+35 score in <a class='font-bold interactive text-ui-100'>Valorant Competitive Ladder</a>",
      },
      {
        text: "<a class='font-bold interactive text-ui-100'>2 missions</a> completed",
      },
      {
        text: "<a class='font-bold interactive text-ui-100'>1 achievement</a> unlocked",
      },
    ],
  },
  {
    id: 1,
    user: 1,
    meta: {
      game: 1,
      mode: "Competitive",
      map: 7,
      agent: 17,
      dateTimeStarted: "",
      dateTimeEnded: "1 hour ago",
      duration: "38m 26s",
      averageRank: 4,
      text: "First time playing Yoru. I suck 😅",
      media: {
        url: "https://res.cloudinary.com/gloot/video/upload/v1691602551/Stryda/demo/game%20footage/012854044DD9DD911_0_3.final.mp4",
      },
    },
    stats: {
      hasWon: false,
      time: "08:10 PM",
      duration: "24m 12s",
      score: {
        team1: 11,
        team2: 12,
      },
      mainStats: [
        {
          label: "Placement",
          value: "#7",
        },
        {
          label: "K/D/A",
          value: "17/17/10",
        },
        {
          label: "K/D",
          value: "1.00",
        },
        {
          label: "ADR",
          value: "175",
        },
        {
          label: "ACS",
          value: "175",
        },
        {
          label: "HS%",
          value: "15.4%",
        },
        {
          label: "KAST",
          value: "64.0%",
        },
      ],
      leaderboard: {
        team1: [
          {
            id: 0,
            agent: 3,
            nickname: "FriendlyFire",
            tag: "2410",
            rank: 6,
            isPlus: true,
          },
          {
            id: 1,
            agent: 5,
            nickname: "shikari",
            tag: "1901",
            rank: 5,
            isPlus: true,
          },
          {
            id: 2,
            agent: 1,
            nickname: "glenn",
            tag: "2321",
            rank: 3,
            isPlus: false,
          },
          {
            id: 3,
            agent: 6,
            nickname: "sooshy",
            tag: "2321",
            rank: 2,
            isPlus: false,
          },
          {
            id: 4,
            agent: 7,
            nickname: "sabsab",
            tag: "2321",
            rank: 1,
            isPlus: false,
          },
        ],
        team2: [
          {
            id: 0,
            agent: 2,
            nickname: "quickyKiller",
            tag: "2413",
            rank: 7,
            isPlus: true,
          },
          {
            id: 1,
            agent: 5,
            nickname: "InifintyWar",
            tag: "1197",
            rank: 5,
            isPlus: true,
          },
          {
            id: 2,
            agent: 9,
            nickname: "glenn",
            tag: "2321",
            rank: 3,
            isPlus: false,
          },
          {
            id: 3,
            agent: 10,
            nickname: "sooshy",
            tag: "2321",
            rank: 2,
            isPlus: false,
          },
          {
            id: 4,
            agent: 11,
            nickname: "sabsab",
            tag: "2321",
            rank: 1,
            isPlus: false,
          },
        ],
      },
    },
  },
  {
    id: 2,
    user: 5,
    meta: {
      game: 1,
      mode: "Competitive",
      map: 3,
      agent: 10,
      dateTimeStarted: "",
      dateTimeEnded: "3 hours ago",
      duration: "38m 26s",
      averageRank: 4,
      text: "😭😭😭😭",
      media: {
        url: "https://res.cloudinary.com/gloot/video/upload/v1691649709/Stryda/demo/game%20footage/42E1C90460381BAD1_0_3.final.mp4",
      },
    },
    stats: {
      hasWon: false,
      time: "08:10 PM",
      duration: "24m 12s",
      score: {
        team1: 11,
        team2: 12,
      },
      mainStats: [
        {
          label: "Placement",
          value: "#8",
        },
        {
          label: "K/D/A",
          value: "17/17/10",
        },
        {
          label: "K/D",
          value: "1.00",
        },
        {
          label: "ADR",
          value: "175",
        },
        {
          label: "ACS",
          value: "175",
        },
        {
          label: "HS%",
          value: "15.4%",
        },
        {
          label: "KAST",
          value: "64.0%",
        },
      ],
      leaderboard: {
        team1: [
          {
            id: 0,
            agent: 3,
            nickname: "FriendlyFire",
            tag: "2410",
            rank: 6,
            isPlus: true,
          },
          {
            id: 1,
            agent: 5,
            nickname: "shikari",
            tag: "1901",
            rank: 5,
            isPlus: true,
          },
          {
            id: 2,
            agent: 1,
            nickname: "glenn",
            tag: "2321",
            rank: 3,
            isPlus: false,
          },
          {
            id: 3,
            agent: 6,
            nickname: "sooshy",
            tag: "2321",
            rank: 2,
            isPlus: false,
          },
          {
            id: 4,
            agent: 7,
            nickname: "sabsab",
            tag: "2321",
            rank: 1,
            isPlus: false,
          },
        ],
        team2: [
          {
            id: 0,
            agent: 2,
            nickname: "quickyKiller",
            tag: "2413",
            rank: 7,
            isPlus: true,
          },
          {
            id: 1,
            agent: 5,
            nickname: "InifintyWar",
            tag: "1197",
            rank: 5,
            isPlus: true,
          },
          {
            id: 2,
            agent: 9,
            nickname: "glenn",
            tag: "2321",
            rank: 3,
            isPlus: false,
          },
          {
            id: 3,
            agent: 10,
            nickname: "sooshy",
            tag: "2321",
            rank: 2,
            isPlus: false,
          },
          {
            id: 4,
            agent: 11,
            nickname: "sabsab",
            tag: "2321",
            rank: 1,
            isPlus: false,
          },
        ],
      },
    },
  },
  {
    id: 3,
    user: 5,
    meta: {
      game: 1,
      mode: "Competitive",
      map: 8,
      agent: 10,
      dateTimeStarted: "",
      dateTimeEnded: "3 hours ago",
      duration: "38m 26s",
      averageRank: 4,
      text: "We won on Lotus",
      media: {
        url: "https://res.cloudinary.com/gloot/video/upload/v1691649706/Stryda/demo/game%20footage/DA9DA6B4CC7894931_0_3.final.mp4",
      },
    },
    stats: {
      hasWon: true,
      time: "08:10 PM",
      duration: "24m 12s",
      score: {
        team1: 12,
        team2: 5,
      },
      mainStats: [
        {
          label: "Placement",
          value: "#7",
        },
        {
          label: "K/D/A",
          value: "17/17/10",
        },
        {
          label: "K/D",
          value: "1.00",
        },
        {
          label: "ADR",
          value: "175",
        },
        {
          label: "ACS",
          value: "175",
        },
        {
          label: "HS%",
          value: "15.4%",
        },
        {
          label: "KAST",
          value: "64.0%",
        },
      ],
      leaderboard: {
        team1: [
          {
            id: 0,
            agent: 3,
            nickname: "FriendlyFire",
            tag: "2410",
            rank: 6,
            isPlus: true,
          },
          {
            id: 1,
            agent: 5,
            nickname: "shikari",
            tag: "1901",
            rank: 5,
            isPlus: true,
          },
          {
            id: 2,
            agent: 1,
            nickname: "glenn",
            tag: "2321",
            rank: 3,
            isPlus: false,
          },
          {
            id: 3,
            agent: 6,
            nickname: "sooshy",
            tag: "2321",
            rank: 2,
            isPlus: false,
          },
          {
            id: 4,
            agent: 7,
            nickname: "sabsab",
            tag: "2321",
            rank: 1,
            isPlus: false,
          },
        ],
        team2: [
          {
            id: 0,
            agent: 2,
            nickname: "quickyKiller",
            tag: "2413",
            rank: 7,
            isPlus: true,
          },
          {
            id: 1,
            agent: 5,
            nickname: "InifintyWar",
            tag: "1197",
            rank: 5,
            isPlus: true,
          },
          {
            id: 2,
            agent: 9,
            nickname: "glenn",
            tag: "2321",
            rank: 3,
            isPlus: false,
          },
          {
            id: 3,
            agent: 10,
            nickname: "sooshy",
            tag: "2321",
            rank: 2,
            isPlus: false,
          },
          {
            id: 4,
            agent: 11,
            nickname: "sabsab",
            tag: "2321",
            rank: 1,
            isPlus: false,
          },
        ],
      },
    },
  },
  {
    id: 4,
    user: 3,
    meta: {
      game: 1,
      mode: "Competitive",
      map: 4,
      agent: 6,
      dateTimeStarted: "",
      dateTimeEnded: "3 hours ago",
      duration: "15m 12s",
      averageRank: 4,
      text: "They got crushed",
      media: {
        url: "https://res.cloudinary.com/gloot/video/upload/v1691649700/Stryda/demo/game%20footage/2D4EC5F4050A780C1_0_3.final.mp4",
      },
    },
    stats: {
      hasWon: true,
      time: "08:10 PM",
      duration: "24m 12s",
      score: {
        team1: 12,
        team2: 5,
      },
      mainStats: [
        {
          label: "Placement",
          value: "#5",
        },
        {
          label: "K/D/A",
          value: "17/17/10",
        },
        {
          label: "K/D",
          value: "1.00",
        },
        {
          label: "ADR",
          value: "175",
        },
        {
          label: "ACS",
          value: "175",
        },
        {
          label: "HS%",
          value: "15.4%",
        },
        {
          label: "KAST",
          value: "64.0%",
        },
      ],
      leaderboard: {
        team1: [
          {
            id: 0,
            agent: 3,
            nickname: "FriendlyFire",
            tag: "2410",
            rank: 6,
            isPlus: true,
          },
          {
            id: 1,
            agent: 5,
            nickname: "shikari",
            tag: "1901",
            rank: 5,
            isPlus: true,
          },
          {
            id: 2,
            agent: 1,
            nickname: "glenn",
            tag: "2321",
            rank: 3,
            isPlus: false,
          },
          {
            id: 3,
            agent: 6,
            nickname: "sooshy",
            tag: "2321",
            rank: 2,
            isPlus: false,
          },
          {
            id: 4,
            agent: 7,
            nickname: "sabsab",
            tag: "2321",
            rank: 1,
            isPlus: false,
          },
        ],
        team2: [
          {
            id: 0,
            agent: 2,
            nickname: "quickyKiller",
            tag: "2413",
            rank: 7,
            isPlus: true,
          },
          {
            id: 1,
            agent: 5,
            nickname: "InifintyWar",
            tag: "1197",
            rank: 5,
            isPlus: true,
          },
          {
            id: 2,
            agent: 9,
            nickname: "glenn",
            tag: "2321",
            rank: 3,
            isPlus: false,
          },
          {
            id: 3,
            agent: 10,
            nickname: "sooshy",
            tag: "2321",
            rank: 2,
            isPlus: false,
          },
          {
            id: 4,
            agent: 11,
            nickname: "sabsab",
            tag: "2321",
            rank: 1,
            isPlus: false,
          },
        ],
      },
    },
  },
  {
    id: 5,
    user: 11,
    meta: {
      game: 1,
      mode: "Unrated",
      map: 5,
      agent: 15,
      dateTimeStarted: "",
      dateTimeEnded: "5 hours ago",
      duration: "15m 12s",
      averageRank: 4,
      text: "Shock Dart!",
    },
    stats: {
      hasWon: true,
      time: "08:10 PM",
      duration: "28m 12s",
      score: {
        team1: 12,
        team2: 10,
      },
      mainStats: [
        {
          label: "Placement",
          value: "#2",
        },
        {
          label: "K/D/A",
          value: "17/17/10",
        },
        {
          label: "K/D",
          value: "1.00",
        },
        {
          label: "ADR",
          value: "175",
        },
        {
          label: "ACS",
          value: "175",
        },
        {
          label: "HS%",
          value: "15.4%",
        },
        {
          label: "KAST",
          value: "64.0%",
        },
      ],
      leaderboard: {
        team1: [
          {
            id: 0,
            agent: 3,
            nickname: "FriendlyFire",
            tag: "2410",
            rank: 6,
            isPlus: true,
          },
          {
            id: 1,
            agent: 5,
            nickname: "shikari",
            tag: "1901",
            rank: 5,
            isPlus: true,
          },
          {
            id: 2,
            agent: 1,
            nickname: "glenn",
            tag: "2321",
            rank: 3,
            isPlus: false,
          },
          {
            id: 3,
            agent: 6,
            nickname: "sooshy",
            tag: "2321",
            rank: 2,
            isPlus: false,
          },
          {
            id: 4,
            agent: 7,
            nickname: "sabsab",
            tag: "2321",
            rank: 1,
            isPlus: false,
          },
        ],
        team2: [
          {
            id: 0,
            agent: 2,
            nickname: "quickyKiller",
            tag: "2413",
            rank: 7,
            isPlus: true,
          },
          {
            id: 1,
            agent: 5,
            nickname: "InifintyWar",
            tag: "1197",
            rank: 5,
            isPlus: true,
          },
          {
            id: 2,
            agent: 9,
            nickname: "glenn",
            tag: "2321",
            rank: 3,
            isPlus: false,
          },
          {
            id: 3,
            agent: 10,
            nickname: "sooshy",
            tag: "2321",
            rank: 2,
            isPlus: false,
          },
          {
            id: 4,
            agent: 11,
            nickname: "sabsab",
            tag: "2321",
            rank: 1,
            isPlus: false,
          },
        ],
      },
    },
    achievements: [
      {
        text: "+200 score in <a class='font-bold interactive text-ui-100'>Valorant Unrated Ladder</a>",
      },
      {
        text: "<a class='font-bold interactive text-ui-100'>2 achievements</a> unlocked",
      },
    ],
  },
  {
    id: 6,
    user: 3,
    meta: {
      game: 1,
      mode: "Unrated",
      map: 7,
      agent: 9,
      dateTimeStarted: "",
      dateTimeEnded: "5 hours ago",
      duration: "15m 12s",
      averageRank: 4,
    },
    stats: {
      hasWon: false,
      time: "08:10 PM",
      duration: "28m 12s",
      score: {
        team1: 12,
        team2: 13,
      },
      mainStats: [
        {
          label: "Placement",
          value: "#3",
        },
        {
          label: "K/D/A",
          value: "17/17/10",
        },
        {
          label: "K/D",
          value: "1.00",
        },
        {
          label: "ADR",
          value: "175",
        },
        {
          label: "ACS",
          value: "175",
        },
        {
          label: "HS%",
          value: "15.4%",
        },
        {
          label: "KAST",
          value: "64.0%",
        },
      ],
      leaderboard: {
        team1: [
          {
            id: 0,
            agent: 3,
            nickname: "FriendlyFire",
            tag: "2410",
            rank: 6,
            isPlus: true,
          },
          {
            id: 1,
            agent: 5,
            nickname: "shikari",
            tag: "1901",
            rank: 5,
            isPlus: true,
          },
          {
            id: 2,
            agent: 1,
            nickname: "glenn",
            tag: "2321",
            rank: 3,
            isPlus: false,
          },
          {
            id: 3,
            agent: 6,
            nickname: "sooshy",
            tag: "2321",
            rank: 2,
            isPlus: false,
          },
          {
            id: 4,
            agent: 7,
            nickname: "sabsab",
            tag: "2321",
            rank: 1,
            isPlus: false,
          },
        ],
        team2: [
          {
            id: 0,
            agent: 2,
            nickname: "quickyKiller",
            tag: "2413",
            rank: 7,
            isPlus: true,
          },
          {
            id: 1,
            agent: 5,
            nickname: "InifintyWar",
            tag: "1197",
            rank: 5,
            isPlus: true,
          },
          {
            id: 2,
            agent: 9,
            nickname: "glenn",
            tag: "2321",
            rank: 3,
            isPlus: false,
          },
          {
            id: 3,
            agent: 10,
            nickname: "sooshy",
            tag: "2321",
            rank: 2,
            isPlus: false,
          },
          {
            id: 4,
            agent: 11,
            nickname: "sabsab",
            tag: "2321",
            rank: 1,
            isPlus: false,
          },
        ],
      },
    },
    achievements: [
      {
        text: "<a class='font-bold interactive text-ui-100'>1 achievement</a> unlocked",
      },
    ],
  },
];
