export const dataUsers = [
  {
    id: 1,
    isYou: true,
    isPremium: false,
    isFollower: false,
    isFollowing: false,
    level: 145,
    isOnline: true,
    nickname: "CtrlChampion",
    firstname: "John",
    lastname: "JoKes",
    country: "Trinidad and Tobago",
    countryFlag: "tt",
    lang: "ENG",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1655292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_5.jpg",
    email: "ctrlchampion@gmail.com",
    clan: 1,
    bio: "Hi, I'm Jack, I love to play VALORANT & CS:GO with my friends. I was born in 1976 but I move my mouse quicker than anyone. I have 7 children that I named based on my favorite games: Link, Mario, Zelda, Kane, Fox, Raiden and Valentine.",
    socials: {
      riotValorantNickname: "CtrlChampion",
      riotValorantHashtag: 8573,
      riotLeagueofLegendsNickname: "CtrlChampion",
      riotLeagueofLegendsHashtag: 8573,
      discord: "@ctrlchamp",
      twitch: "@ctrlchamp",
      steam: "@ctrlchamp",
    },
    shopItems: {
      avatarFrame: 3,
      profileBanner: 34,
    },
    stats: {
      xp: 10000,
      playedLadders: 14,
      avgPlacement: 32,
      avgScore: 532,
      timesInTop: 3,
      completedMissions: 558,
      highlightViews: 558,
      playedTournaments: 12,
      followers: 43,
      followings: 65,
      gamestats: [
        {
          game: 1,
          winrate: "25%",
          kdratio: "0.81",
          headshotkillsavg: "1.14",
          assistavg: "2.3",
        },
        {
          game: 2,
          winrate: "40%",
          kdratio: "1.4",
          headshotkillsavg: "1.87",
          assistavg: "2.3",
        },
      ],
    },
    wallet: {
      coins: 15300,
      tokens: 2187,
      powertokens: 105,
      tickets: 3,
    },
    games: [1, 6, 4],
    ladders: [
      {
        gameSlug: "valorant",
        id: 1,
      },
      {
        gameSlug: "pubg",
        id: 2,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
    ],
    achievements: {
      favoriteBadge: 2,
      badges: [
        {
          id: 1,
          item: 1,
          level: 1,
          percent: 80,
          progress: 10,
          from: "9",
          to: "10",
        },
        {
          id: 2,
          item: 2,
          level: 2,
          percent: 50,
          progress: 16,
          from: "20",
          to: "30",
        },
        {
          id: 3,
          item: 3,
          level: 4,
          percent: 80,
          progress: 10,
          from: "90",
          to: "100",
        },
        {
          id: 16,
          item: 22,
          level: 5,
          percent: 80,
          progress: 20,
          from: "10",
          to: "10",
        },
        {
          id: 16,
          item: 21,
          level: 5,
          percent: 99,
          progress: 1,
          from: "100",
          to: "100",
        },
        {
          id: 4,
          item: 4,
          level: 5,
          percent: 100,
          progress: 0,
          from: "1",
          to: "1",
        },
        {
          id: 5,
          item: 5,
          level: 5,
          percent: 100,
          progress: 0,
          from: "3015",
          to: "1000",
        },
        {
          id: 6,
          item: 6,
          level: 5,
          percent: 90,
          progress: 10,
          from: "10",
          to: "10",
        },
        {
          id: 7,
          item: 7,
          level: 0,
          percent: 0,
          progress: 0,
          from: "0",
          to: "5",
        },
        {
          id: 8,
          item: 8,
          level: 0,
          percent: 0,
          progress: 0,
          from: "0",
          to: "1",
        },
        {
          id: 9,
          item: 9,
          level: 0,
          percent: 0,
          progress: 0,
          from: "0",
          to: "666",
        },
        {
          id: 10,
          item: 10,
          level: 0,
          percent: 0,
          progress: 0,
          from: "0",
          to: "1",
        },
        {
          id: 11,
          item: 11,
          level: 0,
          percent: 0,
          progress: 0,
          from: "0",
          to: "1",
        },
        {
          id: 12,
          item: 12,
          level: 0,
          percent: 0,
          progress: 0,
          from: "0",
          to: "1",
        },
        {
          id: 13,
          item: 13,
          level: 0,
          percent: 0,
          progress: 0,
          from: "0",
          to: "1",
        },
        {
          id: 14,
          item: 14,
          level: 0,
          percent: 0,
          progress: 0,
          from: "0",
          to: "700",
        },
        {
          id: 15,
          item: 15,
          level: 0,
          percent: 0,
          progress: 0,
          from: "0",
          to: "1",
        },
      ],
    },
    friends: [2, 3, 4, 5, 6, 7, 8, 9, 10],
    videos: [
      {
        id: 0,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/ED08E6E4D05877E81_0_3.final.mp4",
        },
        date: "1 day ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: true,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 12,
            team2: 9,
          },
        },
        social: {
          views: "1.4k",
        },
      },
      {
        id: 1,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/E5988314326A00D41_0_3.final.mp4",
        },
        date: "2 days ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: true,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 12,
            team2: 9,
          },
        },
        social: {
          views: "1.4k",
        },
      },
      {
        id: 2,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/C9BF9C6456592A001_0_3.final.mp4",
        },
        date: "1 week ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: false,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 8,
            team2: 12,
          },
        },
        social: {
          views: "1.1k",
        },
      },
      {
        id: 3,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1691649725/Stryda/demo/game%20footage/4BFBEDE4D6EB046B1_0_3.final.mp4",
        },
        date: "1 month ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: true,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 12,
            team2: 9,
          },
        },
        social: {
          views: "0.5k",
        },
      },
    ],
  },
  {
    id: 2,
    isYou: false,
    isPremium: true,
    isFollower: false,
    isFollowing: false,
    level: 75,
    isOnline: false,
    nickname: "MrEmptyState",
    firstname: "Kees",
    lastname: "Empty",
    country: "Germany",
    countryFlag: "de",
    lang: "ENG",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1655292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_1.jpg",
    email: "kes@gmail.com",
    clan: null,
    socials: {},
    shopItems: {
      avatarFrame: false,
      profileBanner: false,
    },
    stats: {
      xp: false,
      playedLadders: false,
      avgPlacement: false,
      avgScore: false,
      timesInTop: false,
      completedMissions: false,
      highlightViews: false,
      playedTournaments: false,
      followers: 0,
      followings: 0,
      gamestats: [
        {
          game: 2,
          winrate: "25%",
          kdratio: "0.81",
          headshotkillsavg: "1.14",
          assistavg: "2.3",
        },
        {
          game: 3,
          winrate: "40%",
          kdratio: "1.4",
          headshotkillsavg: "1.87",
          assistavg: "2.3",
        },
      ],
    },
    wallet: {
      coins: 50000,
      tokens: 245,
      powertokens: 15,
      tickets: 3,
    },
    games: [1],
    achievements: {
      favoriteBadge: false,
      badges: [],
    },
  },
  {
    id: 3,
    isYou: false,
    isPremium: false,
    isFollower: true,
    isFollowing: false,
    isLive:
      "https://res.cloudinary.com/gloot/video/upload/v1691649700/Stryda/demo/game%20footage/2D4EC5F4050A780C1_0_3.final.mp4",
    level: 4,
    isOnline: true,
    nickname: "elligator256",
    firstname: "Johna",
    lastname: "Mapp",
    country: "Grenada",
    countryFlag: "gd",
    lang: "ENG",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1655292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_2.jpg",
    avatarFrame: 3,
    email: "mrkil@gmail.com",
    clan: 1,
    bio: "Extreme alcohol guru. Hardcore troublemaker. Food lover. Musicaholic. Typical social media geek.",
    socials: {
      riotValorantNickname: "MrKilla",
      riotValorantHashtag: 8573,
      riotLeagueofLegendsNickname: "MrKilla",
      riotLeagueofLegendsHashtag: 8573,
      discord: "@misterkilla",
      twitch: "@misterkilla",
      steam: "@misterkilla",
    },
    shopItems: {
      avatarFrame: 3,
      profileBanner: 21,
    },
    stats: {
      xp: 9275,
      playedLadders: 243,
      avgPlacement: 32,
      avgScore: 532,
      timesInTop: 3,
      completedMissions: 558,
      highlightViews: 558,
      followers: 52,
      followings: 23,
      playedTournaments: 22,
    },
    wallet: {
      coins: 50000,
      tokens: 245,
      powertokens: 15,
      tickets: 3,
    },
    games: [1],
    ladders: [
      {
        gameSlug: "valorant",
        id: 1,
      },
      {
        gameSlug: "pubg",
        id: 2,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
    ],
    achievements: {
      favoriteBadge: 4,
      badges: [],
    },
    friends: [4, 8, 11],
    videos: [
      {
        id: 0,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/ED08E6E4D05877E81_0_3.final.mp4",
        },
        date: "1 day ago",
        stats: {
          views: "1.4k",
        },
      },
      {
        id: 1,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/E5988314326A00D41_0_3.final.mp4",
        },
        date: "2 days ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: true,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 12,
            team2: 9,
          },
        },
        social: {
          views: "1.4k",
        },
      },
      {
        id: 2,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/C9BF9C6456592A001_0_3.final.mp4",
        },
        date: "1 week ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: false,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 8,
            team2: 12,
          },
        },
        social: {
          views: "1.1k",
        },
      },
      {
        id: 3,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1691649725/Stryda/demo/game%20footage/4BFBEDE4D6EB046B1_0_3.final.mp4",
        },
        date: "1 month ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: true,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 12,
            team2: 9,
          },
        },
        social: {
          views: "0.5k",
        },
      },
    ],
  },
  {
    id: 4,
    isYou: false,
    isPremium: false,
    isFollower: true,
    isFollowing: false,
    isLive:
      "https://res.cloudinary.com/gloot/video/upload/v1691649700/Stryda/demo/game%20footage/2D4EC5F4050A780C1_0_3.final.mp4",
    level: 198,
    isOnline: true,
    nickname: "Shikari",
    firstname: "Jojo",
    lastname: "Mitsotakis",
    country: "Greece",
    countryFlag: "gr",
    lang: "ENG",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1655292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_3.jpg",
    email: "shikari@gmail.com",
    clan: 2,
    bio: "Do not disturb, I am Gaming.",
    socials: {
      riotValorantNickname: "shikari",
      riotValorantHashtag: 1901,
      riotLeagueofLegendsNickname: "shikari",
      riotLeagueofLegendsHashtag: 1901,
      discord: "@shikari",
      twitch: "@shikari",
      steam: "@shikari",
    },
    shopItems: {
      avatarFrame: 5,
      profileBanner: 33,
    },
    stats: {
      xp: 18970,
      playedLadders: 14,
      avgPlacement: 32,
      avgScore: 532,
      timesInTop: 3,
      completedMissions: 558,
      highlightViews: 558,
      followers: 147,
      followings: 2523,
      playedTournaments: 12,

      gamestats: [
        {
          game: 1,
          winrate: "25%",
          kdratio: "0.81",
          headshotkillsavg: "1.14",
          assistavg: "2.3",
        },
      ],
    },
    wallet: {
      coins: 50000,
      tokens: 245,
      powertokens: 15,
      tickets: 3,
    },
    games: [1, 6],
    ladders: [
      {
        gameSlug: "valorant",
        id: 2,
      },
      {
        gameSlug: "leagueoflegends",
        id: 2,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
    ],
    achievements: {
      favoriteBadge: 2,
      badges: [
        {
          id: 1,
          item: 1,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 2,
          item: 2,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 3,
          item: 3,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 4,
          item: 4,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
      ],
    },
    friends: [4, 8, 11],
    videos: [
      {
        id: 0,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/ED08E6E4D05877E81_0_3.final.mp4",
        },
        date: "1 day ago",
        stats: {
          views: "1.4k",
        },
      },
      {
        id: 1,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/E5988314326A00D41_0_3.final.mp4",
        },
        date: "2 days ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: true,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 12,
            team2: 9,
          },
        },
        social: {
          views: "1.4k",
        },
      },
      {
        id: 2,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/C9BF9C6456592A001_0_3.final.mp4",
        },
        date: "1 week ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: false,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 8,
            team2: 12,
          },
        },
        social: {
          views: "1.1k",
        },
      },
      {
        id: 3,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1691649725/Stryda/demo/game%20footage/4BFBEDE4D6EB046B1_0_3.final.mp4",
        },
        date: "1 month ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: true,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 12,
            team2: 9,
          },
        },
        social: {
          views: "0.5k",
        },
      },
    ],
  },
  {
    id: 5,
    isYou: false,
    isPremium: false,
    isFollower: true,
    isFollowing: false,
    level: 42,
    isOnline: false,
    nickname: "Johnny",
    firstname: "Johnny",
    lastname: "Deep",
    country: "United States",
    countryFlag: "us",
    lang: "ENG",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1655292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_4.jpg",
    email: "dirtyjohnny@gmail.com",
    clan: 1,
    bio: "Nothing epic happens in real life, so I chose to be a gamer.",
    socials: {
      riotValorantNickname: "DirtyJohnny",
      riotValorantHashtag: 8573,
      discord: "@dirtyjohnny",
      twitch: "@dirtyjohnny",
      steam: "@dirtyjohnny",
    },
    shopItems: {
      avatarFrame: 2,
      profileBanner: 11,
    },
    stats: {
      xp: 874,
      playedLadders: 3,
      avgPlacement: 32,
      avgScore: 532,
      timesInTop: 3,
      completedMissions: 558,
      highlightViews: 558,
      playedTournaments: 0,
      followers: 143,
      followings: 153,
      gamestats: [
        {
          game: 2,
          winrate: "25%",
          kdratio: "0.81",
          headshotkillsavg: "1.14",
          assistavg: "2.3",
        },
        {
          game: 3,
          winrate: "40%",
          kdratio: "1.4",
          headshotkillsavg: "1.87",
          assistavg: "2.3",
        },
      ],
    },
    wallet: {
      coins: 532,
      tokens: 759,
      powertokens: 15,
      tickets: 3,
    },
    games: [1, 2],
    ladders: [
      {
        gameSlug: "valorant",
        id: 3,
      },
      {
        gameSlug: "pubg",
        id: 2,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
    ],
    achievements: {
      favoriteBadge: 2,
      badges: [
        {
          id: 1,
          item: 1,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 2,
          item: 2,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 3,
          item: 3,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 4,
          item: 4,
          level: 5,
          percent: 90,
          progress: 10,
          from: "900",
          to: "1000",
        },
      ],
    },
    friends: [4, 8, 11],
    videos: [
      {
        id: 0,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/ED08E6E4D05877E81_0_3.final.mp4",
        },
        date: "1 day ago",
        stats: {
          views: "1.4k",
        },
      },
      {
        id: 1,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/E5988314326A00D41_0_3.final.mp4",
        },
        date: "2 days ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: true,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 12,
            team2: 9,
          },
        },
        social: {
          views: "1.4k",
        },
      },
      {
        id: 2,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/C9BF9C6456592A001_0_3.final.mp4",
        },
        date: "1 week ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: false,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 8,
            team2: 12,
          },
        },
        social: {
          views: "1.1k",
        },
      },
      {
        id: 3,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1691649725/Stryda/demo/game%20footage/4BFBEDE4D6EB046B1_0_3.final.mp4",
        },
        date: "1 month ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: true,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 12,
            team2: 9,
          },
        },
        social: {
          views: "0.5k",
        },
      },
    ],
  },
  {
    id: 6,
    isYou: false,
    isPremium: false,
    isFollower: true,
    isFollowing: false,
    level: 15,
    isOnline: false,
    nickname: "PopoRob",
    firstname: "Rob",
    lastname: "Williams",
    country: "United Kingdom",
    countryFlag: "gb",
    lang: "ENG",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1655292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_6.jpg",
    email: "robbiewilliams@gmail.com",
    clan: 1,
    bio: "Hi everyone! My name is PopoRob, but around the Internet I go by Zentouro (don’t ask, its a weird story involving an elven name generator when I was 8). I’m an Environmental Studies major at Middlebury College, focusing in Film and Media Culture. I also have minors in Chinese and Computer Science.",
    socials: {
      riotValorantNickname: "PopoRob",
      riotValorantHashtag: 8573,
      discord: "@poporob",
      twitch: "@poporob",
      steam: "@poporob",
    },
    shopItems: {
      avatarFrame: 1,
      profileBanner: false,
    },
    stats: {
      xp: 239,
      playedLadders: 74,
      avgPlacement: 32,
      avgScore: 532,
      timesInTop: 3,
      completedMissions: 558,
      highlightViews: 558,
      playedTournaments: 2,
      followers: 2,
      followings: 4,
    },
    wallet: {
      coins: 50000,
      tokens: 245,
      powertokens: 15,
      tickets: 3,
    },
    games: [1],
    ladders: [
      {
        gameSlug: "pubg",
        id: 2,
      },
      {
        gameSlug: "pubg",
        id: 2,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
    ],
    achievements: {
      favoriteBadge: 2,
      badges: [
        {
          id: 1,
          item: 4,
          level: 2,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 2,
          item: 7,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 4,
          item: 3,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
      ],
    },
    friends: [4, 8, 11],
    videos: [
      {
        id: 0,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/ED08E6E4D05877E81_0_3.final.mp4",
        },
        date: "1 day ago",
        stats: {
          views: "1.4k",
        },
      },
      {
        id: 1,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/E5988314326A00D41_0_3.final.mp4",
        },
        date: "2 days ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: true,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 12,
            team2: 9,
          },
        },
        social: {
          views: "1.4k",
        },
      },
      {
        id: 2,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/C9BF9C6456592A001_0_3.final.mp4",
        },
        date: "1 week ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: false,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 8,
            team2: 12,
          },
        },
        social: {
          views: "1.1k",
        },
      },
      {
        id: 3,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1691649725/Stryda/demo/game%20footage/4BFBEDE4D6EB046B1_0_3.final.mp4",
        },
        date: "1 month ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: true,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 12,
            team2: 9,
          },
        },
        social: {
          views: "0.5k",
        },
      },
    ],
  },
  {
    id: 7,
    isYou: false,
    isPremium: false,
    isFollower: true,
    isFollowing: true,
    level: 52,
    isOnline: false,
    nickname: "Valance",
    firstname: "Valérie",
    lastname: "Williams",
    country: "France",
    countryFlag: "fr",
    lang: "ENG",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1655292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_7.jpg",
    email: "valance@gmail.com",
    clan: 4,
    bio: "Gamer. Entrepreneur. Analyst. Hardcore problem solver. Alcohol evangelist. Internet aficionado. Food specialist.",
    socials: {
      riotValorantNickname: "valance",
      riotValorantHashtag: 1425,
      discord: "@valance",
      twitch: "@valance",
      steam: "@valance",
    },
    shopItems: {
      avatarFrame: 110,
      profileBanner: 35,
    },
    stats: {
      xp: 198,
      playedLadders: 15,
      avgPlacement: 32,
      avgScore: 532,
      timesInTop: 3,
      completedMissions: 558,
      highlightViews: 558,
      playedTournaments: 0,
      followers: 54,
      followings: 66,
    },
    wallet: {
      coins: 50000,
      tokens: 245,
      powertokens: 15,
      tickets: 3,
    },
    games: [1],
    ladders: [
      {
        gameSlug: "valorant",
        id: 1,
      },
      {
        gameSlug: "valorant",
        id: 2,
      },
      {
        gameSlug: "pubg",
        id: 2,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
    ],
    achievements: {
      favoriteBadge: 2,
      badges: [
        {
          id: 1,
          item: 4,
          level: 5,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 2,
          item: 7,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 4,
          item: 3,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
      ],
    },
    friends: [4, 8, 11],
    videos: [
      {
        id: 0,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/ED08E6E4D05877E81_0_3.final.mp4",
        },
        date: "1 day ago",
        stats: {
          views: "1.4k",
        },
      },
      {
        id: 1,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/E5988314326A00D41_0_3.final.mp4",
        },
        date: "2 days ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: true,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 12,
            team2: 9,
          },
        },
        social: {
          views: "1.4k",
        },
      },
      {
        id: 2,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/C9BF9C6456592A001_0_3.final.mp4",
        },
        date: "1 week ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: false,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 8,
            team2: 12,
          },
        },
        social: {
          views: "1.1k",
        },
      },
      {
        id: 3,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1691649725/Stryda/demo/game%20footage/4BFBEDE4D6EB046B1_0_3.final.mp4",
        },
        date: "1 month ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: true,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 12,
            team2: 9,
          },
        },
        social: {
          views: "0.5k",
        },
      },
    ],
  },
  {
    id: 8,
    isYou: false,
    isPremium: true,
    isFollower: true,
    isFollowing: true,
    isLive:
      "https://res.cloudinary.com/gloot/video/upload/v1691649700/Stryda/demo/game%20footage/2D4EC5F4050A780C1_0_3.final.mp4",
    level: 87,
    isOnline: false,
    nickname: "Pilar",
    firstname: "Steven",
    lastname: "Catterpilar",
    country: "United Kingdom",
    countryFlag: "gb",
    lang: "ENG",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1655292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_8.jpg",
    email: "PilarPilar@gmail.com",
    clan: 1,
    socials: {
      riotLeagueofLegendsNickname: "Pilar",
      riotLeagueofLegendsHashtag: 7482,
      twitch: "@PilarPilar",
      steam: "@PilarPilar",
    },
    shopItems: {
      avatarFrame: false,
      profileBanner: 36,
    },
    stats: {
      xp: 244,
      playedLadders: 54,
      avgPlacement: 32,
      avgScore: 532,
      timesInTop: 3,
      completedMissions: 558,
      highlightViews: 558,
      playedTournaments: 23,
      followers: 23,
      followings: 76,
    },
    wallet: {
      coins: 50000,
      tokens: 245,
      powertokens: 15,
      tickets: 3,
    },
    games: [4, 6],
    ladders: [
      {
        gameSlug: "valorant",
        id: 2,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
    ],
    achievements: {
      favoriteBadge: 2,
      badges: [
        {
          id: 1,
          item: 1,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 2,
          item: 2,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 3,
          item: 3,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 4,
          item: 4,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
      ],
    },
    friends: [4, 8, 11],
    videos: [
      {
        id: 0,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/ED08E6E4D05877E81_0_3.final.mp4",
        },
        date: "1 day ago",
        stats: {
          views: "1.4k",
        },
      },
      {
        id: 1,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/E5988314326A00D41_0_3.final.mp4",
        },
        date: "2 days ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: true,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 12,
            team2: 9,
          },
        },
        social: {
          views: "1.4k",
        },
      },
      {
        id: 2,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1692013194/Stryda/demo/game%20footage/C9BF9C6456592A001_0_3.final.mp4",
        },
        date: "1 week ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: false,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 8,
            team2: 12,
          },
        },
        social: {
          views: "1.1k",
        },
      },
      {
        id: 3,
        game: 1,
        media: {
          url: "https://res.cloudinary.com/gloot/video/upload/v1691649725/Stryda/demo/game%20footage/4BFBEDE4D6EB046B1_0_3.final.mp4",
        },
        date: "1 month ago",
        stats: {
          agent: 3,
          map: 12,
          hasWon: true,
          time: "08:10 PM",
          duration: "24m 12s",
          score: {
            team1: 12,
            team2: 9,
          },
        },
        social: {
          views: "0.5k",
        },
      },
    ],
  },
  {
    id: 9,
    isYou: false,
    isPremium: false,
    isFollower: false,
    isFollowing: false,
    level: 3,
    isOnline: true,
    nickname: "HansGrubby",
    firstname: "Hans",
    lastname: "Grubber",
    country: "Germany",
    countryFlag: "de",
    lang: "ENG",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1655292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_9.jpg",
    email: "hanshans@gmail.com",
    clan: 6,
    bio: "I'm an unapologetic gamer. Social media enthusiast. Student. Certified alcohol guru. Problem solver. Hardcore twitter maven. Tv evangelist.",
    socials: {
      riotValorantNickname: "HansGrubby",
      riotValorantHashtag: 1254,
      twitch: "@HansGrubby",
      steam: "@HansGrubby",
      twitch: "@HansGrubby",
      steam: "@HansGrubby",
    },
    shopItems: {
      avatarFrame: 102,
      profileBanner: 18,
    },
    stats: {
      xp: 10000,
      playedLadders: 54,
      avgPlacement: 32,
      avgScore: 532,
      timesInTop: 3,
      completedMissions: 558,
      highlightViews: 558,
      playedTournaments: 23,
      followers: 11,
      followings: 23,
    },
    wallet: {
      coins: 50000,
      tokens: 245,
      powertokens: 15,
      tickets: 3,
    },
    games: [1, 2, 3, 4],
    ladders: [
      {
        gameSlug: "valorant",
        id: 1,
      },
      {
        gameSlug: "valorant",
        id: 2,
      },
      {
        gameSlug: "pubg",
        id: 2,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
    ],
    achievements: {
      favoriteBadge: 2,
      badges: [
        {
          id: 1,
          item: 1,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 2,
          item: 2,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 3,
          item: 3,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 4,
          item: 4,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
      ],
    },
  },
  {
    id: 10,
    isYou: false,
    isPremium: false,
    isFollower: false,
    isFollowing: false,
    level: 111,
    isOnline: false,
    nickname: "FrenzyMan",
    firstname: "Scott",
    lastname: "Fritz",
    country: "Austria",
    countryFlag: "at",
    lang: "GER",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1655292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_10.jpg",
    email: "frenzyman@gmail.com",
    clan: 1,
    bio: "Just one more game.",
    socials: {
      riotValorantNickname: "FrenzyMan",
      riotValorantHashtag: 1254,
      discord: "@FrenzyMan",
      twitch: "@FrenzyMan",
      steam: "@FrenzyMan",
    },
    shopItems: {
      avatarFrame: false,
      profileBanner: 2,
    },
    stats: {
      xp: 297,
      playedLadders: 2,
      avgPlacement: 32,
      avgScore: 532,
      timesInTop: 3,
      completedMissions: 558,
      highlightViews: 558,
      playedTournaments: 0,
      followers: 23,
      followings: 42,
    },
    wallet: {
      coins: 50000,
      tokens: 245,
      powertokens: 15,
      tickets: 3,
    },
    games: [1, 5, 3, 4],
  },
  {
    id: 11,
    isYou: false,
    isPremium: true,
    isFollower: false,
    isFollowing: true,
    level: 72,
    isOnline: true,
    nickname: "Joppe",
    firstname: "Johan",
    lastname: "Per",
    country: "Malta",
    countryFlag: "mt",
    lang: "ENG",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1655292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_11.jpg",
    email: "joppe@gmail.com",
    clan: 2,
    bio: "Sleep. Eat. Game. Repeat.",
    socials: {
      riotValorantNickname: "Joppe",
      riotValorantHashtag: 1254,
      riotLeagueofLegendsNickname: "Joppe",
      riotLeagueofLegendsHashtag: 1254,
      discord: "@Joppe",
      twitch: "@Joppe",
    },
    shopItems: {
      avatarFrame: 4,
      profileBanner: 27,
    },
    stats: {
      xp: 297,
      playedLadders: 2,
      avgPlacement: 32,
      avgScore: 532,
      timesInTop: 3,
      completedMissions: 558,
      highlightViews: 558,
      playedTournaments: 0,
      followers: 98,
      followings: 101,
    },
    wallet: {
      coins: 50000,
      tokens: 245,
      powertokens: 15,
      tickets: 3,
    },
    games: [1, 6],
    ladders: [
      {
        gameSlug: "valorant",
        id: 1,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
      {
        gameSlug: "pubg",
        id: 2,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
    ],
    achievements: {
      favoriteBadge: 2,
      badges: [
        {
          id: 1,
          item: 1,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 2,
          item: 2,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 3,
          item: 3,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 4,
          item: 4,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
      ],
    },
  },
  {
    id: 12,
    isYou: false,
    isPremium: true,
    isFollower: false,
    isFollowing: true,
    level: 72,
    isOnline: true,
    nickname: "KooKoo",
    firstname: "Kristian",
    lastname: "Kook",
    country: "France",
    countryFlag: "fr",
    lang: "FR",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1655292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_12.jpg",
    email: "KooKoo@gmail.com",
    clan: 3,
    bio: "Sleep. Eat. Game. Repeat.",
    socials: {
      riotValorantNickname: "KooKoo",
      riotValorantHashtag: 1254,
      riotLeagueofLegendsNickname: "KooKoo",
      riotLeagueofLegendsHashtag: 1254,
      discord: "@KooKoo",
      twitch: "@KooKoo",
      steam: "@KooKoo",
    },
    shopItems: {
      avatarFrame: 160,
      profileBanner: 27,
    },
    stats: {
      xp: 297,
      playedLadders: 2,
      avgPlacement: 32,
      avgScore: 532,
      timesInTop: 3,
      completedMissions: 558,
      highlightViews: 558,
      playedTournaments: 0,
      followers: 55,
      followings: 98,
    },
    wallet: {
      coins: 50000,
      tokens: 245,
      powertokens: 15,
      tickets: 3,
    },
    games: [1, 6, 3],
    ladders: [
      {
        gameSlug: "valorant",
        id: 1,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
      {
        gameSlug: "pubg",
        id: 2,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
    ],
    achievements: {
      favoriteBadge: 2,
      badges: [
        {
          id: 1,
          item: 1,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 2,
          item: 2,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 3,
          item: 3,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 4,
          item: 4,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
      ],
    },
  },
  {
    id: 13,
    isYou: false,
    isPremium: false,
    isFollower: true,
    isFollowing: false,
    level: 72,
    isOnline: false,
    nickname: "KnuckleDust",
    firstname: "Knuckle",
    lastname: "Dust",
    country: "Germany",
    countryFlag: "de",
    lang: "DE",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1655292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_13.jpg",
    email: "KnuckleDust@gmail.com",
    clan: 3,
    bio: "Sleep. Eat. Game. Repeat.",
    socials: {
      riotValorantNickname: "KnuckleDust",
      riotValorantHashtag: 1254,
      riotLeagueofLegendsNickname: "KnuckleDust",
      riotLeagueofLegendsHashtag: 1254,
      discord: "@KnuckleDust",
      twitch: "@KnuckleDust",
      steam: "@KnuckleDust",
    },
    shopItems: {
      avatarFrame: 6,
      profileBanner: 27,
    },
    stats: {
      xp: 297,
      playedLadders: 2,
      avgPlacement: 32,
      avgScore: 532,
      timesInTop: 3,
      completedMissions: 558,
      highlightViews: 558,
      playedTournaments: 0,
      followers: 14,
      followings: 7,
    },
    wallet: {
      coins: 50000,
      tokens: 245,
      powertokens: 15,
      tickets: 3,
    },
    games: [1, 7, 4, 6],
    ladders: [
      {
        gameSlug: "valorant",
        id: 1,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
      {
        gameSlug: "pubg",
        id: 2,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
    ],
    achievements: {
      favoriteBadge: 2,
      badges: [
        {
          id: 1,
          item: 1,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 2,
          item: 2,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 3,
          item: 3,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 4,
          item: 4,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
      ],
    },
  },
  {
    id: 14,
    isYou: false,
    isPremium: false,
    isFollower: true,
    isFollowing: true,
    level: 23,
    isOnline: false,
    nickname: "TechCluster",
    firstname: "Georgiana",
    lastname: "Cluster",
    country: "Germany",
    countryFlag: "de",
    lang: "DE",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1655292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_14.jpg",
    email: "TechCluster@gmail.com",
    clan: 4,
    bio: "Sleep. Eat. Game. Repeat.",
    socials: {
      riotValorantNickname: "TechCluster",
      riotValorantHashtag: 1254,
      riotLeagueofLegendsNickname: "TechCluster",
      riotLeagueofLegendsHashtag: 1254,
      discord: "@TechCluster",
      twitch: "@TechCluster",
    },
    shopItems: {
      avatarFrame: 7,
      profileBanner: 28,
    },
    stats: {
      xp: 297,
      playedLadders: 2,
      avgPlacement: 32,
      avgScore: 532,
      timesInTop: 3,
      completedMissions: 558,
      highlightViews: 558,
      playedTournaments: 0,
      followers: 827,
      followings: 1541,
    },
    wallet: {
      coins: 50000,
      tokens: 245,
      powertokens: 15,
      tickets: 3,
    },
    games: [1, 6],
    ladders: [
      {
        gameSlug: "valorant",
        id: 1,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
      {
        gameSlug: "pubg",
        id: 2,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
    ],
    achievements: {
      favoriteBadge: 2,
      badges: [
        {
          id: 1,
          item: 1,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 2,
          item: 2,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 3,
          item: 3,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 4,
          item: 4,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
      ],
    },
  },
  {
    id: 15,
    isYou: false,
    isPremium: false,
    isFollower: true,
    isFollowing: true,
    level: 23,
    isOnline: false,
    nickname: "Gimiwi",
    firstname: "Pierre",
    lastname: "Garnier",
    country: "Jamaica",
    countryFlag: "jm",
    lang: "JM",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1655292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_15.jpg",
    email: "Gimiwi@gmail.com",
    clan: 5,
    bio: "Sleep. Eat. Game. Repeat.",
    socials: {
      riotValorantNickname: "Gimiwi",
      riotValorantHashtag: 1254,
      riotLeagueofLegendsNickname: "Gimiwi",
      riotLeagueofLegendsHashtag: 1254,
      discord: "@Gimiwi",
      twitch: "@Gimiwi",
      steam: "@Gimiwi",
    },
    shopItems: {
      avatarFrame: 8,
      profileBanner: 29,
    },
    stats: {
      xp: 297,
      playedLadders: 2,
      avgPlacement: 32,
      avgScore: 532,
      timesInTop: 3,
      completedMissions: 558,
      highlightViews: 558,
      playedTournaments: 0,
      followers: 12,
      followings: 2,
    },
    wallet: {
      coins: 50000,
      tokens: 245,
      powertokens: 15,
      tickets: 3,
    },
    games: [6, 1],
    ladders: [
      {
        gameSlug: "valorant",
        id: 1,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
      {
        gameSlug: "pubg",
        id: 2,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
    ],
    achievements: {
      favoriteBadge: 2,
      badges: [
        {
          id: 1,
          item: 1,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 2,
          item: 2,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 3,
          item: 3,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 4,
          item: 4,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
      ],
    },
  },
  {
    id: 16,
    isYou: false,
    isPremium: false,
    isFollower: true,
    isFollowing: true,
    level: 2,
    isOnline: false,
    nickname: "Obtusk",
    firstname: "Pierre",
    lastname: "Garnier",
    country: "Jamaica",
    countryFlag: "jm",
    lang: "JM",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1655292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_16.jpg",
    email: "Obtusk@gmail.com",
    clan: 7,
    bio: "Sleep. Eat. Game. Repeat.",
    socials: {
      riotLeagueofLegendsNickname: "Obtusk",
      riotLeagueofLegendsHashtag: 1254,
      discord: "@Obtusk",
      twitch: "@Obtusk",
      steam: "@Obtusk",
    },
    shopItems: {
      avatarFrame: 9,
      profileBanner: 30,
    },
    stats: {
      xp: 297,
      playedLadders: 2,
      avgPlacement: 32,
      avgScore: 532,
      timesInTop: 3,
      completedMissions: 558,
      highlightViews: 558,
      playedTournaments: 0,
      followers: 44,
      followings: 22,
    },
    wallet: {
      coins: 50000,
      tokens: 245,
      powertokens: 15,
      tickets: 3,
    },
    games: [6],
    ladders: [
      {
        gameSlug: "valorant",
        id: 1,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
      {
        gameSlug: "pubg",
        id: 2,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
    ],
    achievements: {
      favoriteBadge: 2,
      badges: [
        {
          id: 1,
          item: 1,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 2,
          item: 2,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 3,
          item: 3,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 4,
          item: 4,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
      ],
    },
  },
  {
    id: 17,
    isYou: false,
    isPremium: false,
    isFollower: true,
    isFollowing: true,
    level: 2,
    isOnline: false,
    nickname: "YeargLitch",
    firstname: "Ida",
    lastname: "Nilsson",
    country: "Sweden",
    countryFlag: "se",
    lang: "SE",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1755292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_17.jpg",
    email: "YeargLitch@gmail.com",
    clan: 7,
    bio: "Sleep. Eat. Game. Repeat.",
    socials: {
      riotValorantNickname: "YeargLitch",
      riotValorantHashtag: 1254,
      discord: "@YeargLitch",
      twitch: "@YeargLitch",
    },
    shopItems: {
      avatarFrame: null,
      profileBanner: null,
    },
    stats: {
      xp: 297,
      playedLadders: 2,
      avgPlacement: 32,
      avgScore: 532,
      timesInTop: 3,
      completedMissions: 558,
      highlightViews: 558,
      playedTournaments: 0,
      followers: 87,
      followings: 104,
    },
    wallet: {
      coins: 50000,
      tokens: 245,
      powertokens: 15,
      tickets: 3,
    },
    games: [1],
    ladders: [
      {
        gameSlug: "valorant",
        id: 1,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
      {
        gameSlug: "pubg",
        id: 2,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
    ],
    achievements: {
      favoriteBadge: 2,
      badges: [
        {
          id: 1,
          item: 1,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 2,
          item: 2,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 3,
          item: 3,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 4,
          item: 4,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
      ],
    },
  },
  {
    id: 18,
    isYou: false,
    isPremium: false,
    isFollower: true,
    isFollowing: true,
    level: 2,
    isOnline: false,
    nickname: "Minkx",
    firstname: "Dimitar",
    lastname: "Putin",
    country: "Russia",
    countryFlag: "ru",
    lang: "RU",
    avatar:
      "https://res.cloudinary.com/gloot/image/upload/v1755292255/Marketing/2022_prototype/DummyContent/avatars/avatar_user_18.jpg",
    email: "Minkx@gmail.com",
    clan: 8,
    bio: "I luv Putin.",
    socials: {
      discord: "@Minkx",
      twitch: "@Minkx",
      steam: "@Minkx",
    },
    shopItems: {
      avatarFrame: 2,
      profileBanner: 11,
    },
    stats: {
      xp: 297,
      playedLadders: 2,
      avgPlacement: 32,
      avgScore: 532,
      timesInTop: 3,
      completedMissions: 558,
      highlightViews: 558,
      playedTournaments: 0,
      followers: 55,
      followings: 48,
    },
    wallet: {
      coins: 50000,
      tokens: 245,
      powertokens: 15,
      tickets: 3,
    },
    games: [2],
    ladders: [
      {
        gameSlug: "valorant",
        id: 1,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
      {
        gameSlug: "pubg",
        id: 2,
      },
      {
        gameSlug: "valorant",
        id: 3,
      },
    ],
    achievements: {
      favoriteBadge: 2,
      badges: [
        {
          id: 1,
          item: 1,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 2,
          item: 2,
          level: 4,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 3,
          item: 3,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
        {
          id: 4,
          item: 4,
          level: 3,
          percent: 40,
          progress: 10,
          from: "150",
          to: "300",
        },
      ],
    },
  },
];

export default {
  dataUsers,
};
