name: Publish npm package
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - package-npm
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump version and get tag
        id: version_bump
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: 'main,package-npm'
          DEFAULT_BUMP: 'patch'
          WITH_V: true
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v1
        env:
          RUNNER_TEMP: /tmp #TODO: REMOVE THIS BEFORE COMMITING.
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@g-loot' # Defaults to the user or organization that owns the workflow file

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${{ steps.version_bump.outputs.tag }}
      - run: git describe --tag --abbrev=0
      - run: npm --no-git-tag-version version ${{ steps.version_bump.outputs.tag }}

        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
      - run: npm run deploy:framework
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - run: npm run build-storybook
#      - run: npm run deploy
